### ISSUE TITLE
Import arbitrary keys (not tied to identities)

### ISSUE THREAD

**Issue by spiffytech** [ccontavalli/ssh-ident#1]
I cannot deduce from the documentation how to do this, so I assume it's not implemented now.

I would like ssh-ident to be able to use arbitrary keys, without having them tied to identities. Pattern-based identities aren't a great fit for me, as the servers my keys belong to aren't named after any pattern I could match against. 

I already have my ~/.ssh/config set up with specific IdentityFiles for specific hosts (since I'm adding other settings already), and would like ssh-ident to just use whatever key is configured in there for a given host. sshing to these hosts with ssh-ident prompts me for the password for these keys, ssh-ident simply doesn't save the password. Since the keys work, I presume it's possible for ssh-ident to start managing them.

**Comment by ccontavalli** [comment]
If it's of any help, this blog post may help shed some light on why we use ssh-ident:
http://rabexc.org/posts/pitfalls-of-ssh-agents

This article also talks about ssh-ident:
http://www.ct-unlimited.org/2014/04/17/painless-ssh-agent/

I'll mark this issue as Closed, as I don't think there's much I need to do here right now. It's also been 2 years since the bug was opened :)
