### ISSUE TITLE
prints for every shell command

### ISSUE THREAD

**Issue by vindarel** [ccontavalli/ssh-ident#5]
Hi !
I installed and used successfully the master branch of ssh-ident (it's very neat ! It would be cool to have the README formatted though). I set up aliases for ssh and git. 
But now, for every shell command I run (cd, ls,…) ssh-ident prints some output:

    Agent for identity vindarel ready
    All keys already loaded
    Agent for identity vindarel ready
    debug ssh-ident: using identity vindarel
    All keys already loaded

Sure, I can comment out those lines in the code, but I'd like them to show up when I run =ssh= or =git= (only). And it doesn't seem right that ssh-ident is called everytime… An idea ? (I use zsh)
Thanks !

**Comment by black2754** [comment]
I believe, making git an alias to ssh-ident is not a good idea. ssh-ident will try to load keys for every git command, even if it does not require SSH (e.g. because it operates on the local repo only, all remotes are https, ...). Having a symlink named `ssh` in the `$PATH` works much better in this regard.

However, I would like to back up the feature request for a "quiet" option for a different reason.
I use the symlink method and have scp and whatnot call ssh-ident instead of ssh when needed.
Unfortunately, the output of ssh-ident messes up my autocompletion of remote files. Whenever I hit tab, ssh-ident prints "All keys already loaded" or - worse - asks me for my passphrases.

When trying to autocomplete remote files with scp or rsync, zsh calls `ssh` with `-o BatchMode=yes` (bash uses `-o BatchMode yes`). So it might be a good idea for ssh-ident (if `BINARY_SSH` is ssh) to catch that flag and suppress all output and not load keys if this is given. This is what `ssh` would do as well (see `man ssh_config`):
> **BatchMode**
> If set to “yes”, passphrase/password querying will be disabled.  This option is useful in scripts
> and other batch jobs where no user is present to supply the password.  The argument must be “yes”
> or “no”.  The default is “no”.

In addition to this, I would also be happy to have a "quiet" option in the rc file, as ssh-ident is a little too talky for my personal taste.

Carlo, if you don't feel like writing this yourself, I might give it a whirl.

**Comment by uberspot** [comment]
:+1:  for the batch mode and the quiet mode. They would be really handy. 
I would also second  vindarels suggestion for formatting the readme with clean markdown and maybe generating the debian help files from that later on (?).
Nice project overall. :) It's really convenient.

**Comment by ccontavalli** [comment]
Ok, seems like we have consensus, I'm all in favor of following up with the
suggestions here.

Summarizing:
1 - make ssh-ident quiet when BatchMode is used.
2 - add rc option to reduce verbosity.
3 - better formatting for the README file.
(4 - maybe generate debian help / man pages from here).

black2754: if you feel like giving 1 and 2 a whirl, please feel free to do
so, it'd be great to merge in the changes.
Otherwise I can give it a try in a week or two, will ping this issue before
I get started.

Thanks everyone!
Carlo

**Comment by black2754** [comment]
I implemented 1 and 2. Tested with Python 2.7, 3.2, 3.3 and 3.4. Tests and bug reports with the same and other versions are welcome.

Carlo, I took the liberty of reducing the amount of output with the default settings a little bit. You may want to review the loglevels I assigned to the existing messages.

Regards,
Black

**Comment by black2754** [comment]
Ping. Any news on this?

**Comment by ccontavalli** [comment]
Apologies for delay. I went on a 4 weeks trip just after I merged this change in my local copy, and forgot to push. I just pushed it as is, has been working great. I'll probably do some random cleanups over the next few days, but thanks again for contributing the code!!
